# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Running tests

on:
  push:
    branches:
      - master
jobs:
  test_examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run the test examples
        shell: bash -l {0}
        run: |
          pip install seaborn=0.12, mpi4py, pytorch, scikit-learn, rasterio, scikit-image
          cd paseos/examples
          python3 test_examples.py
